"""Running a protocol over data that does not fit in memory.

Three things, in the order a run needs them: how much memory there is
(`budget`), what each step does with it (`contract`), and how the data is
therefore divided up (`plan`). The executor that acts on a plan, the
reconciliation of objects a tile boundary cuts in half, and the
out-of-core measurement table are later phases - see docs/LARGE_IMAGES.md.

Nothing in here changes what an algorithm computes. `label_components` is
still a function that takes a NumPy mask and returns a NumPy label array;
this package decides which NumPy arrays it gets handed.
"""

from vtea_core.blocked.analysis import (
    EstimatorChoice,
    binned_scatter,
    gaussian_mixture_scaled,
    hierarchical_scaled,
    isomap_scaled,
    kmeans_scaled,
    laplacian_eigenmap_scaled,
    pca_scaled,
    should_bin,
    tsne_scaled,
)
from vtea_core.blocked.associate import (
    associate_objects_blocked,
    boundary_distance_blocked,
    boxes_blocked,
    boxes_from_ledger,
    centroid_distance_table,
    centroids_blocked,
    containment_blocked,
    object_ids_blocked,
    score_candidates_blocked,
)
from vtea_core.blocked.budget import (
    CGROUP,
    DETECTED,
    ENV,
    ENV_VAR,
    FALLBACK,
    USER,
    BudgetTooSmall,
    MemoryBudget,
    available_bytes,
    cgroup_limit_bytes,
    detect_memory_budget,
    format_bytes,
    gpu_free_bytes,
    parse_size,
)
from vtea_core.blocked.cells import (
    CellMembership,
    build_cells_blocked,
    cell_features_blocked,
    single_roles_from_links,
)
from vtea_core.blocked.contract import (
    ACCUMULATE,
    APPROXIMATE,
    BLOCK_MODES,
    DEFAULT_SCALING,
    ELEMENTWISE,
    EXACT,
    EXACT_WITH_HALO,
    GLOBAL_STAT,
    NEIGHBORHOOD,
    OBJECT_LOCAL,
    TABLE,
    HaloSpec,
    HaloTooLarge,
    Scaling,
)
from vtea_core.blocked.executor import (
    BlockedPipeline,
    BlockedResult,
    Cancelled,
    NotBlockableYet,
    apply_blocked,
    numpy_pad_mode,
    read_block,
    run_step_blocked,
)
from vtea_core.blocked.gpu import (
    Calibration,
    calibrate,
    calibrated_voxels,
    device_name,
    gpu_plan,
    gpu_tile_voxels,
    is_out_of_memory,
    load_calibration,
    save_calibration,
)
from vtea_core.blocked.ownership import (
    HaloTooSmallForReach,
    SparseOwnership,
    load_sparse_ownership,
    ownership_blocked,
)
from vtea_core.blocked.plan import (
    StepCost,
    Tile,
    TilePlan,
    plan_for_steps,
    plan_tiles,
    step_costs,
    tile_for_region,
)
from vtea_core.blocked.reconcile import (
    ABUTTING,
    CENTROID,
    DEFAULT_POLICY,
    FLAG,
    MERGE,
    NO_MATCHING,
    OVERLAP,
    OVERLAPPING,
    OWN,
    RESEGMENT,
    TOUCHING,
    Fragment,
    HaloExceeded,
    LabelLedger,
    SeamPolicy,
    SeamPolicyError,
    load_ledger,
    save_ledger,
)
from vtea_core.blocked.resume import ManifestMismatch, RunManifest, plan_signature
from vtea_core.blocked.segment import (
    BlockedLabels,
    filter_by_size_blocked,
    segment_blocked,
)
from vtea_core.blocked.stats import ImageStats, otsu_threshold, percentile_threshold, scan
from vtea_core.blocked.store import ZarrScratch

__all__ = [
    "ABUTTING",
    "ACCUMULATE",
    "APPROXIMATE",
    "BLOCK_MODES",
    "CENTROID",
    "CGROUP",
    "DEFAULT_POLICY",
    "DEFAULT_SCALING",
    "DETECTED",
    "ELEMENTWISE",
    "ENV",
    "ENV_VAR",
    "EXACT",
    "EXACT_WITH_HALO",
    "FALLBACK",
    "FLAG",
    "GLOBAL_STAT",
    "MERGE",
    "NEIGHBORHOOD",
    "NO_MATCHING",
    "OBJECT_LOCAL",
    "OVERLAP",
    "OVERLAPPING",
    "OWN",
    "RESEGMENT",
    "TABLE",
    "TOUCHING",
    "USER",
    "BlockedLabels",
    "BlockedPipeline",
    "BlockedResult",
    "BudgetTooSmall",
    "Calibration",
    "Cancelled",
    "CellMembership",
    "EstimatorChoice",
    "Fragment",
    "HaloExceeded",
    "HaloSpec",
    "HaloTooLarge",
    "HaloTooSmallForReach",
    "ImageStats",
    "LabelLedger",
    "ManifestMismatch",
    "MemoryBudget",
    "NotBlockableYet",
    "RunManifest",
    "Scaling",
    "SeamPolicy",
    "SeamPolicyError",
    "SparseOwnership",
    "StepCost",
    "Tile",
    "TilePlan",
    "ZarrScratch",
    "apply_blocked",
    "associate_objects_blocked",
    "available_bytes",
    "binned_scatter",
    "boundary_distance_blocked",
    "boxes_blocked",
    "boxes_from_ledger",
    "build_cells_blocked",
    "calibrate",
    "calibrated_voxels",
    "cell_features_blocked",
    "centroid_distance_table",
    "centroids_blocked",
    "cgroup_limit_bytes",
    "containment_blocked",
    "detect_memory_budget",
    "device_name",
    "filter_by_size_blocked",
    "format_bytes",
    "gaussian_mixture_scaled",
    "gpu_free_bytes",
    "gpu_plan",
    "gpu_tile_voxels",
    "hierarchical_scaled",
    "is_out_of_memory",
    "isomap_scaled",
    "kmeans_scaled",
    "laplacian_eigenmap_scaled",
    "load_calibration",
    "load_ledger",
    "load_sparse_ownership",
    "numpy_pad_mode",
    "object_ids_blocked",
    "otsu_threshold",
    "ownership_blocked",
    "parse_size",
    "pca_scaled",
    "percentile_threshold",
    "plan_for_steps",
    "plan_signature",
    "plan_tiles",
    "read_block",
    "run_step_blocked",
    "save_calibration",
    "save_ledger",
    "scan",
    "score_candidates_blocked",
    "segment_blocked",
    "should_bin",
    "single_roles_from_links",
    "step_costs",
    "tile_for_region",
    "tsne_scaled",
]
